import { MapItem } from "../types/map";

export const historicalPlaces: MapItem[] = [
    {
        id: "1",
        type: "landmark",
        title: "Hagia Sophia",
        description: "Originally built as a Byzantine cathedral in 537 AD and later converted into a mosque.",
        category: "Mosque",
        latitude: 41.0086,
        longitude: 28.9802,
        period: "Byzantine / Ottoman",
    },
    {
        id: "2",
        type: "landmark",
        title: "Blue Mosque",
        description: "Famous Ottoman mosque known for its blue Iznik tiles.",
        category: "Mosque",
        latitude: 41.0055,
        longitude: 28.9768,
        period: "Ottoman",
    },
    {
        id: "3",
        type: "landmark",
        title: "Suleymaniye Mosque",
        description: "A grand mosque designed by the famous Ottoman architect Mimar Sinan.",
        category: "Mosque",
        latitude: 41.0165,
        longitude: 28.9642,
        period: "Ottoman",
    },
    {
        id: "4",
        type: "landmark",
        title: "Topkapi Palace",
        description: "Residence of Ottoman sultans for nearly 400 years.",
        category: "Palace",
        latitude: 41.0115,
        longitude: 28.9833,
        period: "Ottoman",
    },
    {
        id: "5",
        type: "landmark",
        title: "Dolmabahce Palace",
        description: "Lavish Ottoman palace built in the 19th century overlooking the Bosphorus.",
        category: "Palace",
        latitude: 41.0392,
        longitude: 29.0007,
        period: "Ottoman",
    },
    {
        id: "6",
        type: "landmark",
        title: "Beylerbeyi Palace",
        description: "Summer residence of Ottoman sultans on the Asian side of Istanbul.",
        category: "Palace",
        latitude: 41.0423,
        longitude: 29.0404,
        period: "Ottoman",
    },
    {
        id: "7",
        type: "landmark",
        title: "Basilica Cistern",
        description: "Ancient underground water reservoir built during the Byzantine Empire.",
        category: "Museum",
        latitude: 41.0084,
        longitude: 28.9779,
        period: "Byzantine",
    },
    {
        id: "8",
        type: "landmark",
        title: "Galata Tower",
        description: "Medieval stone tower offering panoramic views of Istanbul.",
        category: "Monument",
        latitude: 41.0256,
        longitude: 28.9744,
        period: "Medieval",
    },
    {
        id: "9",
        type: "landmark",
        title: "Hippodrome of Constantinople",
        description: "Ancient stadium used for chariot races during the Byzantine period.",
        category: "Monument",
        latitude: 41.0066,
        longitude: 28.9752,
        period: "Byzantine",
    },
    {
        id: "10",
        type: "landmark",
        title: "Chora Church",
        description: "Famous for its Byzantine mosaics and frescoes.",
        category: "Museum",
        latitude: 41.0317,
        longitude: 28.9392,
        period: "Byzantine",
    },
    {
        id: "11",
        type: "landmark",
        title: "Rumeli Fortress",
        description: "Ottoman fortress built by Sultan Mehmed II before the conquest of Constantinople.",
        category: "Monument",
        latitude: 41.0847,
        longitude: 29.0569,
        period: "Ottoman",
    },
    {
        id: "12",
        type: "landmark",
        title: "Yildiz Palace",
        description: "Late Ottoman palace complex used by Sultan Abdulhamid II.",
        category: "Palace",
        latitude: 41.0471,
        longitude: 29.0169,
        period: "Ottoman",
    },
    {
        id: "13",
        type: "landmark",
        title: "Maiden's Tower",
        description: "Historic tower located on a small islet in the Bosphorus.",
        category: "Monument",
        latitude: 41.0211,
        longitude: 29.0041,
        period: "Byzantine / Ottoman",
    },
    {
        id: "14",
        type: "landmark",
        title: "Grand Bazaar",
        description: "One of the oldest and largest covered markets in the world.",
        category: "Monument",
        latitude: 41.0107,
        longitude: 28.9681,
        period: "Ottoman",
    },
    {
        id: "15",
        type: "landmark",
        title: "Spice Bazaar",
        description: "Historic market famous for spices and Turkish delights.",
        category: "Monument",
        latitude: 41.0169,
        longitude: 28.9700,
        period: "Ottoman",
    },

    {
        id: "16",
        type: "event",
        title: "Conquest of Constantinople",
        description: "The Ottoman conquest of Constantinople in 1453 led by Sultan Mehmed II.",
        category: "Historical Event",
        latitude: 41.0186,
        longitude: 28.9497,
        period: "Ottoman",
    },
    {
        id: "17",
        type: "event",
        title: "Construction of Hagia Sophia",
        description: "Built in 537 AD during the reign of Emperor Justinian I.",
        category: "Historical Event",
        latitude: 41.0086,
        longitude: 28.9802,
        period: "Byzantine",
    },
    {
        id: "18",
        type: "event",
        title: "Nika Revolt",
        description: "A major uprising against Emperor Justinian in 532 AD.",
        category: "Historical Event",
        latitude: 41.0066,
        longitude: 28.9752,
        period: "Byzantine",
    },
    {
        id: "19",
        type: "event",
        title: "Construction of the Blue Mosque",
        description: "Built between 1609 and 1616 under Sultan Ahmed I.",
        category: "Historical Event",
        latitude: 41.0055,
        longitude: 28.9768,
        period: "Ottoman",
    },
    {
        id: "20",
        type: "event",
        title: "Opening of the Grand Bazaar",
        description: "Grand Bazaar began construction shortly after the Ottoman conquest.",
        category: "Historical Event",
        latitude: 41.0107,
        longitude: 28.9681,
        period: "Ottoman",
    }
];